### ISSUE TITLE
StashPop fails to load on PR pages with empty "Non-default test suites" options

### ISSUE THREAD

**Issue by akoeplinger** [dpoeschl/StashPop#77]
One of my colleagues is getting this error in developer console and StashPop doesn't show up:

```
Error in event handler for (unknown): TypeError: Cannot read property 'length' of null
    at processTestFailures (chrome-extension://nghjdgghnnljcdgaicggnlbmojcaedhl/content.js:670:44)
    at addTestFailureButtonsAndDescriptions (chrome-extension://nghjdgghnnljcdgaicggnlbmojcaedhl/content.js:596:9)
    at reloadJenkins (chrome-extension://nghjdgghnnljcdgaicggnlbmojcaedhl/content.js:210:5)
    at chrome-extension://nghjdgghnnljcdgaicggnlbmojcaedhl/content.js:140:13handler @ extensions::uncaught_exception_handler:8
15chrome-extension://nghjdgghnnljcdgaicggnlbmojcaedhl/content.js:303 StashPop:  Permission present.
```

@dpoeschl He didn't have the extension installed before, any idea why this would happen?

**Comment by dpoeschl** [comment]
Investigating, but possibly useful extra info:
- URL they were visiting
- surrounding developer console log

**Comment by akoeplinger** [comment]
Ok, seems like he removed the default entries from "Non-default test suites:" and other lists because he thought they don't apply to us.

**Comment by dpoeschl** [comment]
Wow, that's interesting. Are their options screwed up?

![image](https://cloud.githubusercontent.com/assets/235241/12426819/98587220-be90-11e5-9520-7e3e8fb57eeb.png)

**Comment by dpoeschl** [comment]
Ahh, yeah, I'm not coping well with empty entries there. :frowning: Will fix up.

**Comment by dpoeschl** [comment]
They don't apply to you but are load bearing. :wink:
